sudo: required
services:
    - docker

before_install:
    - docker build -t muyiwa-olaniyi/malvrix-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true muyiwa-olaniyi/malvrix-docker-react npm run test