sudo: required
services:
    - docker

before_install:
    - docker build -t muyiwa-olaniyi/malvrix-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true muyiwa-olaniyi/malvrix-docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "malvrix-docker-react"
    env: "MalvrixDockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-725734769771"
    bucket_path: "malvrix-docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"